/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyApp;

import MyLibs.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Izak
 */
public class MainForm extends javax.swing.JFrame {
    private OfficeMediator officeMed;
    private Office office1;
    private Office office2;
    private Office office3;
    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        officeMed = new OfficeMediator();
        office1 = new Headquarters(officeMed, "Head Office", 6, 20, 50);
        office2 = new CustomerService(officeMed, "Customer Service Branch", 9, 21, 100);
        office3 = new Security(officeMed, "Security Office", 7, 17, 20);
    }
    
    private void showEquipmentList(){
        DefaultTableModel model = (DefaultTableModel) getEquipmentListTbl().getModel();
        model.setRowCount(0);
        for(Equipment e:officeMed.equipmentList){
            String name = e.getName();
            int years = e.getYears();
            String office = e.getOffice();
            String condition = e.getCondition();
            
            model.insertRow(model.getRowCount(), new Object[]{name, years, office, condition});
        }
    }
    
    private void updateTable(){
        DefaultTableModel off1 = (DefaultTableModel) getOffice1Tbl().getModel();
        DefaultTableModel off2 = (DefaultTableModel) getOffice2Tbl().getModel();
        DefaultTableModel off3 = (DefaultTableModel) getOffice3Tbl().getModel();
        DefaultTableModel lost = (DefaultTableModel) getlostTbl().getModel();
        lost.setRowCount(0);
        off1.setRowCount(0);
        off2.setRowCount(0);
        off3.setRowCount(0);
        for(Equipment e:officeMed.equipmentList){
            if(e.getOffice() == office1.getName()){
                String name = e.getName();
                int years = e.getYears();
                String office = e.getOffice();
                String condition = e.getCondition();
                
                off1.insertRow(off1.getRowCount(), new Object[]{name, years, office, condition});
            }
            else if(e.getOffice() == office2.getName()){
                String name = e.getName();
                int years = e.getYears();
                String office = e.getOffice();
                String condition = e.getCondition();
                off2.insertRow(off2.getRowCount(), new Object[]{name, years, office, condition});
            }
            else if(e.getOffice() == office3.getName()){
                String name = e.getName();
                int years = e.getYears();
                String office = e.getOffice();
                String condition = e.getCondition();
                off3.insertRow(off3.getRowCount(), new Object[]{name, years, office, condition});
            }
        }
        showEquipmentList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EquipmentListTbl = new javax.swing.JTable();
        officeLabel1 = new javax.swing.JLabel();
        Office1 = new javax.swing.JScrollPane();
        Office1Tbl = new javax.swing.JTable();
        Office2 = new javax.swing.JScrollPane();
        Office2Tbl = new javax.swing.JTable();
        Office3 = new javax.swing.JScrollPane();
        Office3Tbl = new javax.swing.JTable();
        officeLabel2 = new javax.swing.JLabel();
        officeLabel3 = new javax.swing.JLabel();
        dispEqBtn1 = new javax.swing.JButton();
        AddOffice1Btn = new javax.swing.JButton();
        AddOffice2Btn = new javax.swing.JButton();
        AddOffice3Btn = new javax.swing.JButton();
        lostEqBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lostTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Equipment List");

        EquipmentListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Years", "Office", "Condition"
            }
        ));
        jScrollPane1.setViewportView(EquipmentListTbl);

        officeLabel1.setText("Office1");

        Office1Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Years", "Condition"
            }
        ));
        Office1.setViewportView(Office1Tbl);

        Office2Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Years", "Condition"
            }
        ));
        Office2.setViewportView(Office2Tbl);

        Office3Tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "Years", "Condition"
            }
        ));
        Office3.setViewportView(Office3Tbl);

        officeLabel2.setText("Office2");

        officeLabel3.setText("Office3");

        dispEqBtn1.setText("START");
        dispEqBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dispEqBtn1ActionPerformed(evt);
            }
        });

        AddOffice1Btn.setText("Add to Office1");
        AddOffice1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOffice1BtnActionPerformed(evt);
            }
        });

        AddOffice2Btn.setText("Add to Office2");
        AddOffice2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOffice2BtnActionPerformed(evt);
            }
        });

        AddOffice3Btn.setText("Add to Office3");
        AddOffice3Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddOffice3BtnActionPerformed(evt);
            }
        });

        lostEqBtn.setText("SHOW EQUIPMENT THAT NEEDS ATTENTION");
        lostEqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostEqBtnActionPerformed(evt);
            }
        });

        lostTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(lostTbl);

        jLabel2.setText("Needs repair, lost, or for replacement");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AddOffice1Btn)
                                .addComponent(Office1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(officeLabel1))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(officeLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Office2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AddOffice2Btn))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(officeLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(AddOffice3Btn)
                                            .addComponent(Office3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lostEqBtn)
                                            .addComponent(dispEqBtn1))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(207, 207, 207))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(officeLabel1)
                    .addComponent(officeLabel2)
                    .addComponent(officeLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Office1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Office2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Office3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dispEqBtn1)
                        .addGap(18, 18, 18)
                        .addComponent(lostEqBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddOffice1Btn)
                    .addComponent(AddOffice2Btn)
                    .addComponent(AddOffice3Btn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dispEqBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dispEqBtn1ActionPerformed
        showEquipmentList();
    }//GEN-LAST:event_dispEqBtn1ActionPerformed

    private void AddOffice1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOffice1BtnActionPerformed
        if(EquipmentListTbl.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Select an equipment first!");
        }
        else{
            DefaultTableModel model1 = (DefaultTableModel) getEquipmentListTbl().getModel();
            DefaultTableModel model2 = (DefaultTableModel) getOffice1Tbl().getModel();
            int col = 0;
            int row = EquipmentListTbl.getSelectedRow();
            String x = model1.getValueAt(row, col).toString();
            for(Equipment e:officeMed.equipmentList){
                if(e.getName() == x){
                    office1.addEquipment(office1, e);
                }
            }
            updateTable();
        }
    }//GEN-LAST:event_AddOffice1BtnActionPerformed

    private void AddOffice2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOffice2BtnActionPerformed
        if(EquipmentListTbl.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Select an equipment first!");
        }
        else{
            DefaultTableModel model1 = (DefaultTableModel) getEquipmentListTbl().getModel();
            DefaultTableModel model2 = (DefaultTableModel) getOffice2Tbl().getModel();
            int col = 0;
            int row = EquipmentListTbl.getSelectedRow();
            String x = model1.getValueAt(row, col).toString();
            for(Equipment e:officeMed.equipmentList){
                if(e.getName() == x){
                    office2.addEquipment(office2, e);
                }
            }
            updateTable();
        }
    }//GEN-LAST:event_AddOffice2BtnActionPerformed

    private void AddOffice3BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddOffice3BtnActionPerformed
        if(EquipmentListTbl.getSelectedRow() < 0){
            JOptionPane.showMessageDialog(null, "Select an equipment first!");
        }
        else{
            DefaultTableModel model1 = (DefaultTableModel) getEquipmentListTbl().getModel();
            DefaultTableModel model2 = (DefaultTableModel) getOffice3Tbl().getModel();
            int col = 0;
            int row = EquipmentListTbl.getSelectedRow();
            String x = model1.getValueAt(row, col).toString();
            for(Equipment e:officeMed.equipmentList){
                if(e.getName() == x){
                    office3.addEquipment(office3, e);
                }
            }
            updateTable();
        }
    }//GEN-LAST:event_AddOffice3BtnActionPerformed

    private void lostEqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostEqBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) getlostTbl().getModel();
        model.setRowCount(0);
        for(Equipment e:officeMed.equipmentList){
            if((e.getCondition() == "replacement or lost") || (e.getCondition() == "needs repair")){
                String name = e.getName();
                int years = e.getYears();
                String office = e.getOffice();
                String condition = e.getCondition();
                
                model.insertRow(model.getRowCount(), new Object[]{name, years, office, condition});
            }
        }
    }//GEN-LAST:event_lostEqBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddOffice1Btn;
    private javax.swing.JButton AddOffice2Btn;
    private javax.swing.JButton AddOffice3Btn;
    private javax.swing.JTable EquipmentListTbl;
    private javax.swing.JScrollPane Office1;
    private javax.swing.JTable Office1Tbl;
    private javax.swing.JScrollPane Office2;
    private javax.swing.JTable Office2Tbl;
    private javax.swing.JScrollPane Office3;
    private javax.swing.JTable Office3Tbl;
    private javax.swing.JButton dispEqBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton lostEqBtn;
    private javax.swing.JTable lostTbl;
    private javax.swing.JLabel officeLabel1;
    private javax.swing.JLabel officeLabel2;
    private javax.swing.JLabel officeLabel3;
    // End of variables declaration//GEN-END:variables

    public JTable getEquipmentListTbl() {
        return EquipmentListTbl;
    }

    public void setEquipmentListTbl(JTable EquipmentListTbl) {
        this.EquipmentListTbl = EquipmentListTbl;
    }
    
    public JTable getOffice1Tbl() {
        return Office1Tbl;
    }

    public void setOffice1Tbl(JTable Office1Tbl) {
        this.Office1Tbl = Office1Tbl;
    }
    
    public JTable getOffice2Tbl() {
        return Office2Tbl;
    }

    public void setOffice2Tbl(JTable Office2Tbl) {
        this.Office2Tbl = Office2Tbl;
    }
    
    public JTable getOffice3Tbl() {
        return Office3Tbl;
    }

    public void setOffice3Tbl(JTable Office3Tbl) {
        this.Office3Tbl = Office3Tbl;
    }
    
    public JTable getlostTbl() {
        return lostTbl;
    }

    public void setlostTbl(JTable lostTbl) {
        this.lostTbl = lostTbl;
    }
}
